ALTER TABLE "Server" ADD COLUMN IF NOT EXISTS "clientUrl" TEXT;
ALTER TABLE "Server" ADD COLUMN IF NOT EXISTS "patchUrl" TEXT;
ALTER TABLE "Server" ADD COLUMN IF NOT EXISTS "updaterUrl" TEXT;
ALTER TABLE "Server" ADD COLUMN IF NOT EXISTS "installGuide" TEXT;
